### ISSUE TITLE
Windows wheels

### ISSUE THREAD

**Issue by Dobatymo** [alesanfra/dlib-wheels#2]
Hi, thank you for building and deploying these wheel files. Would it be possible to add Windows builds also?

**Comment by alesanfra** [comment]
Hi @Dobatymo, thanks for your interest in this project. I've drafted a PR to enable windows builds (you can take a look [here](https://github.com/alesanfra/dlib-wheels/pull/3)), however I don't have a windows machine to test them at the moment. Would you mind to try to install them and check if they work properly? You can download them from this link: https://github.com/alesanfra/dlib-wheels/suites/11533732996/artifacts/596751788

**Comment by Dobatymo** [comment]
Hi, thanks for your quick response! The PR looks good to me. I ran the pytest suite using the wheel files from the artifacts using python 3.7, 3.8, 3.9 and 3.10. All succeeded!

Do you think enabling AVX `USE_AVX_INSTRUCTIONS=1` would be fine?

**Comment by alesanfra** [comment]
Great news, I'm going to merge the PR then. I've added a mechanism to overwrite the dlib version in order to publish these new wheels as version 19.24.1. This way the already published 19.24.0 wheels will stay on pypi.org untouched, so that we minimize the risk of breaking projects with pinned dependencies. @Dobatymo thank you for finding the time to run the test suite, really appreciated.

**Comment by alesanfra** [comment]
Regarding the AVX instructions, I'm not really familiar with that flag, what are the advantages of enabling it? Is it available for all three operating systems? What's the practical impact on the users?

In my opinion if the impact is minimal (e.g. all OSs supported, last 10 years CPUs supported) we can just enable it without further ado; on the contrary, in case this flag will to substantially restrict the availability of `dlib-bin`, I believe we should follow a different strategy. Unfortunately, as far as I know, pip doesn't offer a clean way to select different "editions" of the same wheel, the way is usually implemented in other projects is to create a separate name-space (`dlib-bin-avx`?).

Anyway, I would move this discussion to a separate issue, @Dobatymo could you take care of creating a new one? This way we could link the new issue to a PR, if needed. Thanks :)
