### ISSUE TITLE
Create builds with AVX enabled

### ISSUE THREAD

**Issue by Dobatymo** [alesanfra/dlib-wheels#4]
Using `USE_AVX_INSTRUCTIONS=1` will enable the wheel to be compiled with AVX instructions. To quote http://dlib.net/compile.html "For example, if you are using dlib's face detector then you should turn on either SSE4 or AVX instructions since this makes it run much faster". Most CPUs since 2011 support AVX https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX but there is a handful of low-cost CPUs which do not. So I agree that it probably should be published in additional to the original wheel files (under eg. `dlib-bin-avx`) since, like you mentioned, there is no support in pip for different versions.

**Comment by alesanfra** [comment]
In the last couple of days I digged a little bit into the topic and I found this line in the release note of dlib v19.13:

> Made the Python extension module automatically enable AVX instructions if the host machine supports them.  So you never need to say --yes USE_AVX_INSTRUCTIONS anymore when installing dlib.

You can find the original release notes [here](https://github.com/davisking/dlib/blob/v19.24/docs/docs/release_notes.xml#L326).

This distribution started with v19.21, so chances are that dlib-bin had always included AVX instructions in its binary files. But I wanted to double check, so I downloaded the latest wheel published a few days ago, with no surprise I found some AVX instructions within the binary!

You can try yourself with the following commands (I'm using python 3.8 on macOS, on different platforms some names are different):

```shell
pip download dlib-bin
unzip dlib_bin-19.24.1-cp38-cp38-macosx_10_9_x86_64.whl
objdump -d _dlib_pybind11.cpython-38-darwin.so > dlib.asm
cat dlib.asm | grep vextractf128
```

Part of the output (truncated):

```shell
  8f058b: c4 e3 7d 19 fa 01            	vextractf128	$1, %ymm7, %xmm2
  8f1fe2: c4 63 7d 19 ed 01            	vextractf128	$1, %ymm13, %xmm5
  8f1ff4: c4 e3 7d 19 cf 01            	vextractf128	$1, %ymm1, %xmm7
  911cb5: c4 63 7d 19 c0 01            	vextractf128	$1, %ymm8, %xmm0
  911cbf: c4 63 7d 19 fb 01            	vextractf128	$1, %ymm15, %xmm3
  918e25: c4 63 7d 19 c0 01            	vextractf128	$1, %ymm8, %xmm0
  918e2f: c4 63 7d 19 fb 01            	vextractf128	$1, %ymm15, %xmm3
```

So, in the end, I don't think there is anything to do here, maybe the only action could be to document this in the README.md for future references.

**Comment by Dobatymo** [comment]
Great. Thank you for looking into this. The dlib readme on github sets the AVX flag so I missed that it's not necessary anymore. So yes, documenting this for future reference would be good.
