### ISSUE TITLE
No matching distribution found for dlib-bin (Python 3.11)

### ISSUE THREAD

**Issue by bri-vax** [alesanfra/dlib-wheels#6]
pip install dlib-bin
ERROR: Could not find a version that satisfies the requirement dlib-bin (from versions: none)
ERROR: No matching distribution found for dlib-bin

**Comment by alesanfra** [comment]
Hi @bri-vax, thank you for your interest in `dlib-bin`, I added python 3.11 to the build pipeline, please let me know if there are any issues with the distribution.

Alessio
